version: "3.2"
services:
  rabbit:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - BUCKET_STATIC=${BUCKET_STATIC}
      - BUCKET_MEDIA=${BUCKET_MEDIA}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  app:
    build: .
    ports:
      - "8000:8000"
    command: ./run.sh
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER}
      - SITE_DOMAIN=${SITE_DOMAIN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_ENV_NAME=${APP_ENV_NAME}
      - BUCKET_STATIC=${BUCKET_STATIC}
      - BUCKET_MEDIA=${BUCKET_MEDIA}
      - RABBITMQ_HOST=rabbit
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - BUCKET_STATIC_CUSTOM_DOMAIN=${BUCKET_STATIC_CUSTOM_DOMAIN}
      - BUCKET_MEDIA_CUSTOM_DOMAIN=${BUCKET_MEDIA_CUSTOM_DOMAIN}
    depends_on:
      - localstack
      - postgres
      - rabbit
  app_local:
    build: .
    ports:
      - "8000:8000"
    command: ./run.sh
    container_name: app_local
    env_file:
      - .env
    depends_on:
      - localstack
      - postgres
      - rabbit
  app_test:
    build: .
    ports:
      - "8000:8000"
    command: make test
    container_name: app_test
    network_mode: host
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=localhost
      - DB_PORT=${DB_PORT}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER}
      - SITE_DOMAIN=${SITE_DOMAIN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_ENV_NAME=${APP_ENV_NAME}
      - BUCKET_STATIC=${BUCKET_STATIC}
      - BUCKET_MEDIA=${BUCKET_MEDIA}
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - EMAIL_SERVICE_API_KEY=${EMAIL_SERVICE_API_KEY}
    depends_on:
      - localstack
      - postgres
      - rabbit
